name: Mirror & Update

on:
  schedule:
    - cron: '0 * * * *' # run every hour
  workflow_dispatch: # run on workflow dispatch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # Configure git
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      # Clone Fedora mesa source code
      - name: Clone Fedora repo
        run: |
          git clone --single-branch --branch rawhide https://src.fedoraproject.org/rpms/mesa.git fedora-mesa
          cd fedora-mesa
          git remote add upstream https://src.fedoraproject.org/rpms/mesa.git
          git fetch upstream rawhide

          # Clone Github repo
          cd ..
          git clone --single-branch --branch rawhide https://github.com/JMarcosHP/mesa-custom.git github-mesa || true
          cd github-mesa
          git fetch origin rawhide || true

      # Check for changes
      - name: Check for changes
        id: check
        run: |
          FEDORA_COMMIT=$(cd fedora-mesa && git rev-parse upstream/rawhide)
          GITHUB_COMMIT=$(cd github-mesa && git rev-parse origin/rawhide || echo "none")

          echo "Fedora latest commit: $FEDORA_COMMIT"
          echo "GitHub latest commit: $GITHUB_COMMIT"

          if [ "$FEDORA_COMMIT" != "$GITHUB_COMMIT" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi

      # Finish workflow if no changes found
      - name: Skip if no changes
        if: env.HAS_CHANGES == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "No changes detected. Exiting."

      # Push to GitHub
      - name: Push to GitHub
        if: env.HAS_CHANGES == 'true'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd fedora-mesa
          git remote set-url origin https://{GITHUB_TOKEN}@github.com/JMarcosHP/mesa-custom.git
          git push --force origin rawhide:rawhide

