name: Mirror & Update

on:
  schedule:
    - cron: '0 * * * *' # run every hour
  workflow_dispatch: # run on workflow dispatch

jobs:
  mirror:
    runs-on: fedora-latest

    steps:
      # Install git
      - name: Install git
        run: dnf install git

      # Configure git
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      # Clone Fedora mesa source code
      - name: Clone Fedora repo
        run: |
          git clone --single-branch --branch rawhide https://src.fedoraproject.org/rpms/mesa.git
          cd mesa
          git remote add upstream https://src.fedoraproject.org/rpms/mesa.git
          git fetch upstream rawhide

      # Check for changes
      - name: Check for changes
        id: changes
        run: |
          cd mesa
          git fetch upstream rawhide+
          git diff --exit-code upstream/rawhide || echo "Changes found"
        # Use output to determine changes
        env:
          HAS_CHANGES: $([[ "$(git diff --name-only upstream/rawhide)" != "" ]] && echo "true" || echo "false")

      # Finish workflow if no changes found
      - name: Skip if no changes
        if: steps.changes.outputs.HAS_CHANGES == 'false'
        run: echo "No changes detected. Exiting."

      # Push to GitHub
      - name: Push to GitHub
        if: steps.changes.outputs.HAS_CHANGES == 'true'
        run: |
          cd mesa
          git remote add mirror https://github.com/JMarcosHP/mesa-custom.git
          git push --force mirror rawhide:rawhide

